const GLOBALVARS: any = {};
GLOBALVARS.MEAL_TYPE = ["FOOD", "MEDICINE", "WATER", "OTHERS"];
GLOBALVARS.AMOUNT_FOOD = [
  "NA",
  "3 CARROT",
  "2 CARROT",
  "1 CARROT",
  "4/4 CUP",
  "3/4 CUP",
  "2/4 CUP",
  "1/4 CUP",
  "OTHERS",
];
GLOBALVARS.AMOUNT_MEDICINE = ["NA", "OTHERS"];
GLOBALVARS.AMOUNT_WATER = ["NA", "250 ML", "500 ML", "OTHERS"];
GLOBALVARS.STATUS_LIVE = "LIVE";
GLOBALVARS.STATUS_DELETED = "DELETED";

// error messages
GLOBALVARS.ERR_MSG_POSTING_ENTRY = "ERRx0001: Error submitting entry.";
GLOBALVARS.ERR_MSG_GET_ENTRY_DB = "ERRx0002: Error getting entry database id.";

// cookie names
GLOBALVARS.ENTRY_DB_ID = "entryDbId";
GLOBALVARS.DATE_PAGE_URL = "datePageUrl";

export default GLOBALVARS;
